version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:8081"
    links:
      - mongo
  mongo:
    image: mongo:3.4
    volumes: 
      - mongodb:/data/db
    ports:
      - "27017:27017"

volumes: 
  mongodb: