version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
      - './client/public:/client/public'
    ports:
      - "8081:8081"
    links:
      - mongo
  mongo:
    image: mongo:3.4
    volumes: 
      - mongodb:/data/db
    ports:
      - "27017:27017"

volumes: 
  mongodb: